version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace:cached
      - bundle_data:/home/user/.bundle
      - rvm_data:/home/user/.rvm
    hostname: dev
    environment:
      RAILSBLOGSAMPLE_DATABASE_PASSWORD: 123456

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  db_data:
  bundle_data:
  rvm_data:
